env:
  es2021: true
  node: true
  jest: true

plugins:
  - '@stylistic'

extends:
  - plugin:@stylistic/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle:
    - error
    - allow:
        - __dirname
        - __filename
